void api_delay(int frame);
void api_arm(int CMD,int Param);
void api_bgrange(int min_x,int min_y,int max_x,int max_y);
void api_bgpos(int x,int y);
void api_setdoor();
void api_clralldoor();
void api_chkdoor();
void api_clrdoor();
void api_wpal_tile(int PalID,int PalPtr);
void api_return();